SUPABASE_URL = "https://yefgzjyucevhhgruhuqu.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZmd6anl1Y2V2aGhncnVodXF1Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MTIxOTM3MiwiZXhwIjoyMDc2Nzk1MzcyfQ.DVHfIG7Els3uGGjmBUo3UX9VsBlQaAMWBiY5U2FfM2w"
# or (fallback)
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllZmd6anl1Y2V2aGhncnVodXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjEyMTkzNzIsImV4cCI6MjA3Njc5NTM3Mn0.bZ2mNoYDuKkZg7hApGvyhdsgJOSou9EffEEku-c07aU"
SUPABASE_SCHEMA = "public"
APP_SECRET = "12345678900987654321"